name: Daily Issues Report

on:
  schedule:
    - cron: '0 0 * * *' # 毎日UTCの00:00（日本時間で午前9時に相当）に実行
  workflow_dispatch: # これを追加する

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Issues for Each Branch
        run: |
          echo "Fetching issues for each branch..."
          BRANCHES=$(git branch -r | sed 's/origin\///') # リモートブランチのリストを取得
          for branch in $BRANCHES; do
            ISSUES=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" "https://api.github.com/repos/DELAxGithub/slackgithub/issues?state=open&labels=$branch")
            if [ "$ISSUES" != "[]" ]; then # イシューがある場合のみ処理
              ISSUES_LIST=$(echo "$ISSUES" | jq -r '.[] | "- [" + .title + "](" + .html_url + ")"')
              SLACK_MESSAGE+="*${branch}*\n$ISSUES_LIST\n"
            fi
          done
          echo "$SLACK_MESSAGE" > $GITHUB_ENV

      - name: Post to Slack
        if: ${{ env.SLACK_MESSAGE != '' }} # SLACK_MESSAGEが空でない場合のみ実行
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: 'repo,message,commit,author,action,eventName,ref,workflow'
          text: ${{ env.SLACK_MESSAGE }} # 環境変数を使用
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
