name: Daily Issues Report

on:
  schedule:
    - cron: '0 0 * * *' # 毎日UTCの00:00（日本時間で午前9時に相当）に実行

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get unresolved issues from GitHub
  run: |
    echo "Fetching unresolved issues from GitHub"
    ISSUES=$(curl -s -H "Authorization: token ${{ secrets.TOKEN  }}" "https://api.github.com/repos/DELAxGithub/slackgithub/issues?state=open")
    ISSUES_LIST=$(echo "$ISSUES" | jq -r '.[] | "- [" + .title + "](" + .html_url + ")"')
    echo "::set-output name=issues_list::${ISSUES_LIST}"


      - name: Post to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: 'repo,message,commit,author,action,eventName,ref,workflow'
          text: "ここにIssuesリストが入ります"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
