name: Daily Issues Report

on:
  schedule:
    - cron: '0 0 * * *' # Executes at 00:00 UTC (09:00 JST)
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get unresolved issues from GitHub
        id: get_issues
        run: |
          echo "Fetching unresolved issues from GitHub..."
          ISSUES=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" "https://api.github.com/repos/DELAxGithub/slackgithub/issues?state=open&labels=$branch")
          ISSUES_LIST=$(echo "$ISSUES" | jq -r '.[] | select(.state == "open") | "- [" + .title + "](" + .html_url + ")"')
          echo "$ISSUES_LIST" > issues_list.txt

      - name: Read and format issue list
        id: format_issues
        run: |
          ISSUE_MESSAGES=$(cat issues_list.txt)
          echo "Formatted issue list: $ISSUE_MESSAGES"
          echo "ISSUE_MESSAGES<<EOF" >> $GITHUB_ENV
          echo "$ISSUE_MESSAGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post to Slack
        if: env.ISSUE_MESSAGES != ''
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: 'repo,message,commit,author,action,eventName,ref,workflow'
          text: ${{ env.ISSUE_MESSAGES }} # Use the environment variable
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
